FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:18-alpine as production

WORKDIR /app

COPY --from=build /app/node_modules ./node_modules

COPY --from=build /app/dist/src ./dist

COPY package*.json ./

RUN npm install --production

CMD npm run start:prod
